package co.edu.unimayor.srmusicalservidor.datos;
// Generated 29/03/2018 01:10:35 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CancionUsuarioValoracion generated by hbm2java
 */
@Entity
@Table(name = "cancion_usuario_valoracion")
public class CancionUsuarioValoracion implements java.io.Serializable {

    private CancionUsuarioValoracionId id;
    private Cancion cancion;
    private Usuario usuario;
    private Valoracion valoracion;

    public CancionUsuarioValoracion() {
    }

    public CancionUsuarioValoracion(CancionUsuarioValoracionId id, Cancion cancion, Usuario usuario) {
        this.id = id;
        this.cancion = cancion;
        this.usuario = usuario;
    }

    public CancionUsuarioValoracion(CancionUsuarioValoracionId id, Cancion cancion, Usuario usuario, Valoracion valoracion) {
        this.id = id;
        this.cancion = cancion;
        this.usuario = usuario;
        this.valoracion = valoracion;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "cancion", column = @Column(name = "cancion", nullable = false))
        , 
        @AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false))})
    public CancionUsuarioValoracionId getId() {
        return this.id;
    }

    public void setId(CancionUsuarioValoracionId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cancion", nullable = false, insertable = false, updatable = false)
    public Cancion getCancion() {
        return this.cancion;
    }

    public void setCancion(Cancion cancion) {
        this.cancion = cancion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false, insertable = false, updatable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "valoracion")
    public Valoracion getValoracion() {
        return this.valoracion;
    }

    public void setValoracion(Valoracion valoracion) {
        this.valoracion = valoracion;
    }

}
