package co.edu.unimayor.srmusicalservidor.datos;
// Generated 1/04/2018 10:42:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Cancion generated by hbm2java
 */
@Entity
@Table(name = "cancion")
public class Cancion implements java.io.Serializable {

    private Integer id;
    private Estado estadoByEstadoApiRepustate;
    private Estado estadoByEstadoApiTextProcessing;
    private Estado estadoByEstadoApiSentiment140;
    private Estado estadoByEstadoApiSentiment;
    private Estado estadoByEstadoReferencia;
    private String artista;
    private String titulo;
    private String letra;
    private String api;
    private int rankingBillboard;
    private int semanaBillboard;
    private String url;
    private int numeroVisualizacion;
    private int duracionSegundo;
    private double valoracionReferencia;
    private boolean habilitado;
    private Set<CancionUsuarioValoracion> cancionUsuarioValoracions = new HashSet<CancionUsuarioValoracion>(0);

    public Cancion() {
    }

    public Cancion(Estado estadoByEstadoApiRepustate, Estado estadoByEstadoApiTextProcessing, Estado estadoByEstadoApiSentiment140, Estado estadoByEstadoApiSentiment, Estado estadoByEstadoReferencia, String artista, String titulo, String letra, String api, int rankingBillboard, int semanaBillboard, String url, int numeroVisualizacion, int duracionSegundo, double valoracionReferencia, boolean habilitado) {
        this.estadoByEstadoApiRepustate = estadoByEstadoApiRepustate;
        this.estadoByEstadoApiTextProcessing = estadoByEstadoApiTextProcessing;
        this.estadoByEstadoApiSentiment140 = estadoByEstadoApiSentiment140;
        this.estadoByEstadoApiSentiment = estadoByEstadoApiSentiment;
        this.estadoByEstadoReferencia = estadoByEstadoReferencia;
        this.artista = artista;
        this.titulo = titulo;
        this.letra = letra;
        this.api = api;
        this.rankingBillboard = rankingBillboard;
        this.semanaBillboard = semanaBillboard;
        this.url = url;
        this.numeroVisualizacion = numeroVisualizacion;
        this.duracionSegundo = duracionSegundo;
        this.valoracionReferencia = valoracionReferencia;
        this.habilitado = habilitado;
    }

    public Cancion(Estado estadoByEstadoApiRepustate, Estado estadoByEstadoApiTextProcessing, Estado estadoByEstadoApiSentiment140, Estado estadoByEstadoApiSentiment, Estado estadoByEstadoReferencia, String artista, String titulo, String letra, String api, int rankingBillboard, int semanaBillboard, String url, int numeroVisualizacion, int duracionSegundo, double valoracionReferencia, boolean habilitado, Set<CancionUsuarioValoracion> cancionUsuarioValoracions) {
        this.estadoByEstadoApiRepustate = estadoByEstadoApiRepustate;
        this.estadoByEstadoApiTextProcessing = estadoByEstadoApiTextProcessing;
        this.estadoByEstadoApiSentiment140 = estadoByEstadoApiSentiment140;
        this.estadoByEstadoApiSentiment = estadoByEstadoApiSentiment;
        this.estadoByEstadoReferencia = estadoByEstadoReferencia;
        this.artista = artista;
        this.titulo = titulo;
        this.letra = letra;
        this.api = api;
        this.rankingBillboard = rankingBillboard;
        this.semanaBillboard = semanaBillboard;
        this.url = url;
        this.numeroVisualizacion = numeroVisualizacion;
        this.duracionSegundo = duracionSegundo;
        this.valoracionReferencia = valoracionReferencia;
        this.habilitado = habilitado;
        this.cancionUsuarioValoracions = cancionUsuarioValoracions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estado_api_repustate", nullable = false)
    public Estado getEstadoByEstadoApiRepustate() {
        return this.estadoByEstadoApiRepustate;
    }

    public void setEstadoByEstadoApiRepustate(Estado estadoByEstadoApiRepustate) {
        this.estadoByEstadoApiRepustate = estadoByEstadoApiRepustate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estado_api_text_processing", nullable = false)
    public Estado getEstadoByEstadoApiTextProcessing() {
        return this.estadoByEstadoApiTextProcessing;
    }

    public void setEstadoByEstadoApiTextProcessing(Estado estadoByEstadoApiTextProcessing) {
        this.estadoByEstadoApiTextProcessing = estadoByEstadoApiTextProcessing;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estado_api_sentiment140", nullable = false)
    public Estado getEstadoByEstadoApiSentiment140() {
        return this.estadoByEstadoApiSentiment140;
    }

    public void setEstadoByEstadoApiSentiment140(Estado estadoByEstadoApiSentiment140) {
        this.estadoByEstadoApiSentiment140 = estadoByEstadoApiSentiment140;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estado_api_sentiment", nullable = false)
    public Estado getEstadoByEstadoApiSentiment() {
        return this.estadoByEstadoApiSentiment;
    }

    public void setEstadoByEstadoApiSentiment(Estado estadoByEstadoApiSentiment) {
        this.estadoByEstadoApiSentiment = estadoByEstadoApiSentiment;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estado_referencia", nullable = false)
    public Estado getEstadoByEstadoReferencia() {
        return this.estadoByEstadoReferencia;
    }

    public void setEstadoByEstadoReferencia(Estado estadoByEstadoReferencia) {
        this.estadoByEstadoReferencia = estadoByEstadoReferencia;
    }

    @Column(name = "artista", nullable = false, length = 100)
    public String getArtista() {
        return this.artista;
    }

    public void setArtista(String artista) {
        this.artista = artista;
    }

    @Column(name = "titulo", nullable = false, length = 100)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "letra", nullable = false, length = 5000)
    public String getLetra() {
        return this.letra;
    }

    public void setLetra(String letra) {
        this.letra = letra;
    }

    @Column(name = "api", nullable = false, length = 20)
    public String getApi() {
        return this.api;
    }

    public void setApi(String api) {
        this.api = api;
    }

    @Column(name = "ranking_billboard", nullable = false)
    public int getRankingBillboard() {
        return this.rankingBillboard;
    }

    public void setRankingBillboard(int rankingBillboard) {
        this.rankingBillboard = rankingBillboard;
    }

    @Column(name = "semana_billboard", nullable = false)
    public int getSemanaBillboard() {
        return this.semanaBillboard;
    }

    public void setSemanaBillboard(int semanaBillboard) {
        this.semanaBillboard = semanaBillboard;
    }

    @Column(name = "url", nullable = false, length = 150)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "numero_visualizacion", nullable = false)
    public int getNumeroVisualizacion() {
        return this.numeroVisualizacion;
    }

    public void setNumeroVisualizacion(int numeroVisualizacion) {
        this.numeroVisualizacion = numeroVisualizacion;
    }

    @Column(name = "duracion_segundo", nullable = false)
    public int getDuracionSegundo() {
        return this.duracionSegundo;
    }

    public void setDuracionSegundo(int duracionSegundo) {
        this.duracionSegundo = duracionSegundo;
    }

    @Column(name = "valoracion_referencia", nullable = false, precision = 22, scale = 0)
    public double getValoracionReferencia() {
        return this.valoracionReferencia;
    }

    public void setValoracionReferencia(double valoracionReferencia) {
        this.valoracionReferencia = valoracionReferencia;
    }

    @Column(name = "habilitado", nullable = false)
    public boolean isHabilitado() {
        return this.habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cancion")
    public Set<CancionUsuarioValoracion> getCancionUsuarioValoracions() {
        return this.cancionUsuarioValoracions;
    }

    public void setCancionUsuarioValoracions(Set<CancionUsuarioValoracion> cancionUsuarioValoracions) {
        this.cancionUsuarioValoracions = cancionUsuarioValoracions;
    }

}
