package co.edu.unimayor.srmusicalservidor.datos;
// Generated 1/04/2018 10:42:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado")
public class Estado implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private boolean habilitado;
    private Set<Cancion> cancionsForEstadoApiRepustate = new HashSet<Cancion>(0);
    private Set<Cancion> cancionsForEstadoApiTextProcessing = new HashSet<Cancion>(0);
    private Set<Cancion> cancionsForEstadoApiSentiment140 = new HashSet<Cancion>(0);
    private Set<Cancion> cancionsForEstadoApiSentiment = new HashSet<Cancion>(0);
    private Set<Cancion> cancionsForEstadoReferencia = new HashSet<Cancion>(0);

    public Estado() {
    }

    public Estado(String nombre, boolean habilitado) {
        this.nombre = nombre;
        this.habilitado = habilitado;
    }

    public Estado(String nombre, boolean habilitado, Set<Cancion> cancionsForEstadoApiRepustate, Set<Cancion> cancionsForEstadoApiTextProcessing, Set<Cancion> cancionsForEstadoApiSentiment140, Set<Cancion> cancionsForEstadoApiSentiment, Set<Cancion> cancionsForEstadoReferencia) {
        this.nombre = nombre;
        this.habilitado = habilitado;
        this.cancionsForEstadoApiRepustate = cancionsForEstadoApiRepustate;
        this.cancionsForEstadoApiTextProcessing = cancionsForEstadoApiTextProcessing;
        this.cancionsForEstadoApiSentiment140 = cancionsForEstadoApiSentiment140;
        this.cancionsForEstadoApiSentiment = cancionsForEstadoApiSentiment;
        this.cancionsForEstadoReferencia = cancionsForEstadoReferencia;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "nombre", nullable = false, length = 25)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "habilitado", nullable = false)
    public boolean isHabilitado() {
        return this.habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoByEstadoApiRepustate")
    public Set<Cancion> getCancionsForEstadoApiRepustate() {
        return this.cancionsForEstadoApiRepustate;
    }

    public void setCancionsForEstadoApiRepustate(Set<Cancion> cancionsForEstadoApiRepustate) {
        this.cancionsForEstadoApiRepustate = cancionsForEstadoApiRepustate;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoByEstadoApiTextProcessing")
    public Set<Cancion> getCancionsForEstadoApiTextProcessing() {
        return this.cancionsForEstadoApiTextProcessing;
    }

    public void setCancionsForEstadoApiTextProcessing(Set<Cancion> cancionsForEstadoApiTextProcessing) {
        this.cancionsForEstadoApiTextProcessing = cancionsForEstadoApiTextProcessing;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoByEstadoApiSentiment140")
    public Set<Cancion> getCancionsForEstadoApiSentiment140() {
        return this.cancionsForEstadoApiSentiment140;
    }

    public void setCancionsForEstadoApiSentiment140(Set<Cancion> cancionsForEstadoApiSentiment140) {
        this.cancionsForEstadoApiSentiment140 = cancionsForEstadoApiSentiment140;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoByEstadoApiSentiment")
    public Set<Cancion> getCancionsForEstadoApiSentiment() {
        return this.cancionsForEstadoApiSentiment;
    }

    public void setCancionsForEstadoApiSentiment(Set<Cancion> cancionsForEstadoApiSentiment) {
        this.cancionsForEstadoApiSentiment = cancionsForEstadoApiSentiment;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoByEstadoReferencia")
    public Set<Cancion> getCancionsForEstadoReferencia() {
        return this.cancionsForEstadoReferencia;
    }

    public void setCancionsForEstadoReferencia(Set<Cancion> cancionsForEstadoReferencia) {
        this.cancionsForEstadoReferencia = cancionsForEstadoReferencia;
    }

}
