package co.edu.unimayor.srmusicalservidor.datos;
// Generated 1/04/2018 10:42:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

    private Integer id;
    private String cuenta;
    private String contrasena;
    private String nombre;
    private String apellido;
    private String ocupacion;
    private String correo;
    private Long numeroCelular;
    private String direccion;
    private Date fechaNacimiento;
    private boolean habilitado;
    private Set<CancionUsuarioValoracion> cancionUsuarioValoracions = new HashSet<CancionUsuarioValoracion>(0);

    public Usuario() {
    }

    public Usuario(String cuenta, String contrasena, String nombre, boolean habilitado) {
        this.cuenta = cuenta;
        this.contrasena = contrasena;
        this.nombre = nombre;
        this.habilitado = habilitado;
    }

    public Usuario(String cuenta, String contrasena, String nombre, String apellido, String ocupacion, String correo, Long numeroCelular, String direccion, Date fechaNacimiento, boolean habilitado, Set<CancionUsuarioValoracion> cancionUsuarioValoracions) {
        this.cuenta = cuenta;
        this.contrasena = contrasena;
        this.nombre = nombre;
        this.apellido = apellido;
        this.ocupacion = ocupacion;
        this.correo = correo;
        this.numeroCelular = numeroCelular;
        this.direccion = direccion;
        this.fechaNacimiento = fechaNacimiento;
        this.habilitado = habilitado;
        this.cancionUsuarioValoracions = cancionUsuarioValoracions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "cuenta", nullable = false, length = 50)
    public String getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    @Column(name = "contrasena", nullable = false, length = 50)
    public String getContrasena() {
        return this.contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    @Column(name = "nombre", nullable = false, length = 30)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "apellido", length = 30)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Column(name = "ocupacion", length = 20)
    public String getOcupacion() {
        return this.ocupacion;
    }

    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }

    @Column(name = "correo", length = 50)
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Column(name = "numero_celular")
    public Long getNumeroCelular() {
        return this.numeroCelular;
    }

    public void setNumeroCelular(Long numeroCelular) {
        this.numeroCelular = numeroCelular;
    }

    @Column(name = "direccion", length = 100)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_nacimiento", length = 10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Column(name = "habilitado", nullable = false)
    public boolean isHabilitado() {
        return this.habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set<CancionUsuarioValoracion> getCancionUsuarioValoracions() {
        return this.cancionUsuarioValoracions;
    }

    public void setCancionUsuarioValoracions(Set<CancionUsuarioValoracion> cancionUsuarioValoracions) {
        this.cancionUsuarioValoracions = cancionUsuarioValoracions;
    }

}
