package co.edu.unimayor.srmusicalservidor.datos;
// Generated 29/03/2018 01:10:35 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Valoracion generated by hbm2java
 */
@Entity
@Table(name = "valoracion")
public class Valoracion implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private boolean habilitado;
    private Set<CancionUsuarioValoracion> cancionUsuarioValoracions = new HashSet<CancionUsuarioValoracion>(0);
    private Set<Cancion> cancions = new HashSet<Cancion>(0);

    public Valoracion() {
    }

    public Valoracion(String nombre, boolean habilitado) {
        this.nombre = nombre;
        this.habilitado = habilitado;
    }

    public Valoracion(String nombre, boolean habilitado, Set<CancionUsuarioValoracion> cancionUsuarioValoracions, Set<Cancion> cancions) {
        this.nombre = nombre;
        this.habilitado = habilitado;
        this.cancionUsuarioValoracions = cancionUsuarioValoracions;
        this.cancions = cancions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "nombre", nullable = false, length = 15)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "habilitado", nullable = false)
    public boolean isHabilitado() {
        return this.habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "valoracion")
    public Set<CancionUsuarioValoracion> getCancionUsuarioValoracions() {
        return this.cancionUsuarioValoracions;
    }

    public void setCancionUsuarioValoracions(Set<CancionUsuarioValoracion> cancionUsuarioValoracions) {
        this.cancionUsuarioValoracions = cancionUsuarioValoracions;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "valoracion")
    public Set<Cancion> getCancions() {
        return this.cancions;
    }

    public void setCancions(Set<Cancion> cancions) {
        this.cancions = cancions;
    }

}
